steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'builds'
      - 'submit'
      - '--tag'
      - 'asia-south1-docker.pkg.dev/learning-cloud-build-101/gcloud-run-example-repo/gcloud-run-example-img:latest'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gcloud-run-example-service'
      - '--image'
      - 'asia-south1-docker.pkg.dev/learning-cloud-build-101/gcloud-run-example-repo/gcloud-run-example-img:latest'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NAME=SANCHIT'
